indexer/urls.py
from django.contrib import admin
from django.urls import path, include

from indexer import views

app_name = 'indexer'

urlpatterns = [
    path('', views.Index.as_view()),
    path('api/get-status/<int:pk>/', views.GetStatusAPIView.as_view() ),
]

postprodindexer/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('indexer.urls')),

]

indexer/models.py
from django.conf import settings

from django.db import models
from django.http import request
import requests

class PostProdInstance(models.Model):
    region_choices = [
        (1, "Gulf"),
        (2, "Maritimes"),
        (3, "Quebec"),
        (4, "Newfoundland"),
        (5, "Arctic"),
        (6, "O&P"),
    ]

    season = models.PositiveIntegerField(verbose_name="season")
    region = models.PositiveIntegerField(verbose_name="region", choices=region_choices)
    name = models.CharField(max_length=1000, verbose_name="post-production environment name")
    description = models.CharField(max_length=1000, verbose_name="description")
    port = models.PositiveIntegerField(verbose_name="proxy port")
    created_at = models.DateTimeField(auto_now_add=True, editable=False, verbose_name="created at")

    def __str__(self):
        return self.name

    class Meta:
        ordering = ["-season", "region", "name"]


    @property
    def address(self):
        return f"http://{ settings.SITE }:{ self.port }/"

    @property
    def is_alive(self):
        try:
            r = requests.get(self.address, timeout=5)
            return r.status_code == 200
        except:
            return False

indexer/views.py
import django_filters
from django.conf import settings
from django.views.generic import ListView
from django_filters.views import FilterView
from rest_framework import status
from rest_framework.response import Response
from rest_framework.views import APIView

from indexer import models


class MyFilter(django_filters.FilterSet):

    class Meta:
        model = models.PostProdInstance
        fields = {
            'season': ['exact'],
            'region': ['exact'],
            'name': ['icontains'],
            'description': ['icontains'],
        }


class Index(FilterView):
    template_name = 'indexer/index.html'
    model = models.PostProdInstance
    filterset_class = MyFilter

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["SITE"] = settings.SITE
        return context


class GetStatusAPIView(APIView):

    def get(self, request, pk):
        obj = models.PostProdInstance.objects.get(pk=pk)
        return Response(obj.is_alive, status=status.HTTP_200_OK)

indexer/templates/indexer/index.html
{% load bootstrap5 %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset=set"utf-8">
  <meta name="viewport" content="width=device-width">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title></title>
  {% bootstrap_css %}
  {% bootstrap_javascript %}
  <style>
  [v-cloak] {
      display: none;
  }
  </style>

</head>
<body>

<div class="container">

  <div class="text-end mt-5">

{#    <a href="/admin">admin</a>#}

  </div>

  <div class="m-5">
    <h3>Science Container Index</h3>
  </div>


  <div class="m-5" id="app" v-cloak>

    <div class="mb-5">
      <form method="GET">
        <div class="row">
          <div class="col">
            <table class="table table-sm table-bordered">
              {{ filter.form.as_table }}
            </table>
          </div>
          <div class="col">
            <div class="mb-3">
              <button type="submit" class="btn btn-sm btn-warning">Filter</button>
            </div>
            <div class="mb-3">
              <a href="." class="btn btn-sm btn-secondary">Clear</a>
            </div>
          </div>
        </div>

      </form>
    </div>


    <table class="table">

      <thead>

      <tr>
        <th>Season</th>
        <th>Region</th>
        <th>Container name</th>
        <th>Container description</th>
        <th>Link</th>
        <th>Date created</th>
        <th>Status</th>
      </tr>

      </thead>

      <tbody>

      {% for object in object_list %}
        <tr>
          <td>{{ object.season }}</td>
          <td>{{ object.get_region_display }}</td>
          <td>{{ object.name }}</td>
          <td>{{ object.description }}</td>
          <td><a href="{{ object.address }}">{{ object.address }}</a></td>
          <td>{{ object.created_at|date }}</td>
          <td>

            <div v-if="status{{ object.id }} === null">
              <div class="spinner-border mb-3" style="width: 1rem; height: 1rem;" role="status">
                <span class="sr-only"></span>
              </div>
            </div>
            <span v-else-if="status{{ object.id }}" class="px-3" style="background-color: greenyellow; border: 1px black solid"></span>
            <span v-else class="px-3" style="background-color: red; border: 1px black solid"></span>
          </td>
        </tr>
      {% endfor %}


      </tbody>

    </table>
  </div>


</div>
<script src="https://unpkg.com/vue@3/dist/vue.global.js"></script>


<script type="application/javascript">


function getCookie(name) {
  let cookieValue = null;
  if (document.cookie && document.cookie !== '') {
    const cookies = document.cookie.split(';');
    for (let i = 0; i < cookies.length; i++) {
      const cookie = cookies[i].trim();
      // Does this cookie string begin with the name we want?
      if (cookie.substring(0, name.length + 1) === (name + '=')) {
        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
        break;
      }
    }
  }
  return cookieValue;
}


function handleResponse(response) {
  if (response.status === 204) {
    return '';
  } else if (response.status === 404) {
    return null
  } else {
    return response.json();
  }
}


function handleError(error) {
  console.log(`Andes api call encountered the following error: ${error}`);
  if (String(error).toLowerCase().includes("syntaxerror")) {
    alert("Andes encountered an error. Please inform a system administrator or check the logs for more details.")
  }
}

function apiService(endpoint, method, data) {
  const config = {
    method: method || "GET",
    body: data !== undefined ? JSON.stringify(data) : null,
    headers: {
      'content-type': 'application/json',
      'X-CSRFTOKEN': getCookie('csrftoken')
    }
  };
  return fetch(endpoint, config)
      .then(handleResponse)
      .catch(handleError)
}


const {createApp} = Vue

createApp({
  delimiters: ["${", "}"],
  data() {
    return {
      {% for object in object_list %}
        status{{ object.id }}: null,
      {% endfor %}
    }
  },
  methods: {
    getStatus(id) {
      apiService(`api/get-status/${id}/`).then(response => {
        this[`status${id}`] = response
      })
    },

  },
  created() {
    {% for object in object_list %}
      this.getStatus({{ object.id }});
    {% endfor %}
  }
}).mount('#app')

</script>


</body>

</html>